name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
        
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          REMOTE_HOST: "ec2-35-85-152-116.us-west-2.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./var/www/html"
          TARGET: "/var/www/html"
